import "./style.css";
import { invoke } from "@tauri-apps/api/core";
type Device = { serial: string; state: string; model: string };
type Settings = { adb_path: string; scrcpy_path: string; resolution: string; max_fps: number; bitrate: string; desktop_mode: boolean; keep_awake: boolean };
const defaults: Settings = { adb_path: "", scrcpy_path: "", resolution: "1920x1080", max_fps: 60, bitrate: "16M", desktop_mode: true, keep_awake: true };
let settings = { ...defaults, ...JSON.parse(localStorage.getItem("opendex.settings") || "{}") } as Settings;
let launched = new Set<string>(); let starting = new Set<string>(); const app = document.querySelector<HTMLDivElement>("#app")!;
	function render(message = "Waiting for an Android device") { app.innerHTML = `<main><button id="settings" aria-label="Open settings">⚙</button><section class="waiting"><img src="/opendex.png" alt="OpenDex" /><div class="pulse"></div><h1>${message}</h1><p>Connect your phone by USB and approve USB debugging.</p><small>OpenDex will launch automatically.</small><small class="mouse-note">Mouse control is captured by Android. Press <strong>Alt</strong> to release it back to Windows.</small></section><section class="settings" hidden><div><h2>Settings</h2><button id="close" aria-label="Close settings">×</button></div><label>ADB path<input id="adb" value="${settings.adb_path}" placeholder="Use adb from PATH or set a path" /></label><p class="adb-help">Need ADB? Download <a href="https://developer.android.com/tools/releases/platform-tools" target="_blank" rel="noreferrer">Android SDK Platform-Tools for Windows</a>, extract the ZIP, then select its <strong>adb.exe</strong> here or add that folder to PATH. You may also need your phone manufacturer's USB driver.</p><label>scrcpy path<input id="scrcpy" value="${settings.scrcpy_path}" placeholder="Use bundled scrcpy" /></label><label>Max video size<input id="size" value="${settings.resolution}" inputmode="numeric" /></label><label>Frame rate<input id="fps" value="${settings.max_fps}" inputmode="numeric" /></label><label>Bit rate<input id="bitrate" value="${settings.bitrate}" /></label><label class="check"><input id="desktop" type="checkbox" ${settings.desktop_mode ? "checked" : ""} /> Request Samsung desktop mode when supported</label><label class="check"><input id="awake" type="checkbox" ${settings.keep_awake ? "checked" : ""} /> Keep phone awake while connected</label><button id="save">Save</button><p class="privacy">Settings stay on this computer. No account, analytics, or cloud service.</p></section><p id="detail" role="status"></p></main>`; document.querySelector("#settings")?.addEventListener("click", () => (document.querySelector<HTMLElement>(".settings")!.hidden = false)); document.querySelector("#close")?.addEventListener("click", () => (document.querySelector<HTMLElement>(".settings")!.hidden = true)); document.querySelector("#save")?.addEventListener("click", save); }
function addScrcpyHelp() { const input = document.querySelector<HTMLInputElement>("#scrcpy"); if (!input) return; input.placeholder = "Use scrcpy from PATH or set a path"; const help = document.createElement("p"); help.className = "adb-help"; help.innerHTML = 'Need scrcpy? Download the latest <a href="https://github.com/Genymobile/scrcpy/releases" target="_blank" rel="noreferrer">scrcpy Windows release</a>, extract it, then select its <strong>scrcpy.exe</strong> here or add its folder to PATH.'; input.parentElement?.after(help); }
function save() { const get = (id: string) => document.querySelector<HTMLInputElement>(`#${id}`)!; settings = { adb_path: get("adb").value.trim(), scrcpy_path: get("scrcpy").value.trim(), resolution: get("size").value.trim() || defaults.resolution, max_fps: Number(get("fps").value) || defaults.max_fps, bitrate: get("bitrate").value.trim() || defaults.bitrate, desktop_mode: get("desktop").checked, keep_awake: get("awake").checked }; localStorage.setItem("opendex.settings", JSON.stringify(settings)); document.querySelector<HTMLElement>(".settings")!.hidden = true; status("Settings saved."); }
function status(text: string, error = false) { const d = document.querySelector<HTMLParagraphElement>("#detail"); if (d) { d.textContent = text; d.className = error ? "error" : ""; } }
async function watch() { try { const devices = await invoke<Device[]>("list_devices", { adbPath: settings.adb_path || null }); const device = devices.find(d => d.state === "device" && !launched.has(d.serial) && !starting.has(d.serial)); if (!device) return; starting.add(device.serial); render(`Opening ${device.model || "your phone"}…`); addScrcpyHelp(); try { status(await invoke<string>("launch_session", { serial: device.serial, settings })); launched.add(device.serial); } catch (e) { status(String(e), true); } finally { starting.delete(device.serial); } } catch (e) { status(String(e), true); } }
render(); addScrcpyHelp(); void watch(); window.setInterval(() => void watch(), 2000);
